export const landingCopy = {
  ar: {
    discover: 'اكتشف التجربة',
    begin: 'ابدأ الرحلة',
    preview: 'لمحة من الرحلة',
    overviewLabel: 'حكاية تُقرأ، ومكان يُكتشف',
    overviewTitle: 'السيرة النبوية،\nعبر المكان والزمان.',
    overviewBody: 'تعرّف إلى سيرة النبي محمد ﷺ من خلال أحداثها وأماكنها والشخصيات المرتبطة بها. اقرأ الحكاية، وشاهد موضعها على الخريطة، ثم اتبع المصادر لتعرف أكثر.',
    overviewCaption: 'بدء الوحي في غار حراء — الحدث ومكانه في مشهد واحد.',
    overviewAlt: 'لقطة من الرحلة تعرض حدث بدء الوحي إلى جانب غار حراء على الخريطة.',
    tourLabel: 'كيف تبدأ الحكاية؟',
    tourTitle: 'اتبع الحكاية.\nواكتشف ما حولها.',
    tourBody: 'من فصل إلى آخر، تتصل الأحداث بالأماكن، وتصبح تفاصيل السيرة أقرب إلى الفهم.',
    steps: [
      { label: 'اقرأ', title: 'فصلًا بعد فصل،\nتتضح الحكاية.', body: 'ابدأ من قبل البعثة، ثم انتقل إلى العهد المكي والهجرة والعهد المدني. تابع الأحداث بالترتيب، أو اختر الفصل الذي تريد استكشافه.', note: 'أربعة فصول، وخط زمني يجمعها.', caption: 'بداية فصل العهد المكي', alt: 'عنوان فصل العهد المكي ومداه الزمني في صفحة الرحلة.' },
      { label: 'اكتشف', title: 'لكل حدث،\nمكان على الخريطة.', body: 'بينما تقرأ، تتبع الخريطة الحدث وتقرّبك من موضعه حين يكون معلومًا. شاهد كيف تتصل مكة والمدينة وما حولهما بالحكاية.', note: 'المكان والزمان إلى جانب النص.', caption: 'غار حراء على الخريطة التاريخية', alt: 'الخريطة التاريخية مع إبراز غار حراء قرب مكة.' },
      { label: 'تتبّع', title: 'سر مع الرحلة،\nمحطةً بعد محطة.', body: 'استكشف مسار الهجرة، والرحلة إلى الطائف، وحجة الوداع. انتقل بين المحطات الواردة في المصادر، واقرأ النص المرتبط بكل محطة.', note: 'مسارات تُستكشف على مهل.', caption: 'مسار الهجرة النبوية — محطة غار ثور', alt: 'خريطة مسار الهجرة مع بطاقة غار ثور والنص المنقول من مصدره.' },
    ],
    deeperLabel: 'وراء كل حدث، المزيد',
    deeperTitle: 'اقرأ. اسأل.\nوصِل بين التفاصيل.',
    deeperBody: 'حين يلفت انتباهك اسم أو آية أو سؤال، تجد طريقًا لتكمل الاستكشاف.',
    features: [
      { image: 'verses', title: 'الآيات في سياقها', body: 'اطّلع على الآيات المرتبطة بالحدث أو بمرحلته، وافتحها للقراءة مع بيان وجه الارتباط.', alt: 'مراجع سورتي العلق والمدثر المرتبطة ببدء الوحي في بطاقة الحدث.' },
      { image: 'people', title: 'تعرّف إلى الشخصيات', body: 'افتح الأسماء المرتبطة بالحكاية لتقرأ نبذة موثقة، وتصل إلى الأحداث التي تَرِد فيها.', alt: 'نافذة خديجة بنت خويلد رضي الله عنها تعرض اسمها وبداية نبذتها الموثقة.' },
      { image: 'ask', title: 'اسأل الخريطة', body: 'اسأل عن حدث أو مكان أو شخصية. تبحث التجربة في نصوص المشروع وتعرض الإجابة مع مصدرها.', alt: 'إجابة عن وقت غزوة بدر، مستخرجة من نصوص المشروع ومعها الإحالة إلى المصدر.' },
      { image: 'quiz', title: 'اختبر ما اكتشفته', body: 'توقّف عند أسئلة الفصول، واختر المكان على الخريطة. راجع الإجابة والتفسير ثم تابع رحلتك.', alt: 'سؤال من الرحلة مع اختيارات لأماكن على الخريطة.' },
    ],
    sourcesLabel: 'حكاية لها مراجع',
    sourcesTitle: 'اقرأ الحكاية.\nوارجع إلى أصلها.',
    sourcesBody: 'المراجع جزء من التجربة. تجدها إلى جانب النص لتستطيع تتبّع المعلومة وقراءة مصدرها.',
    sourceExample: 'من داخل بطاقة الحدث',
    sourceExampleTitle: 'الهجرة إلى المدينة',
    sourceExampleBody: 'إحالة مباشرة إلى الموسوعة التاريخية، مرفقة بالحدث.',
    sourceAlt: 'إحالة المصدر في بطاقة الهجرة إلى الموسوعة التاريخية للدرر السنية، حدث 42.',
    sources: [
      { title: 'أحداث السيرة', body: 'نصوص من الموسوعة التاريخية للدرر السنية، مع إحالاتها.' },
      { title: 'روايات الحديث', body: 'مراجع من صحيح البخاري وصحيح مسلم للسجلات المرتبطة.' },
      { title: 'الآيات ووجه ارتباطها', body: 'مراجع التفسير وبيان نوع الصلة بين الآيات والأحداث.' },
    ],
    precision: 'بعض المواضع تقريبية، وتُبيّن التجربة دقة الموقع عند عرض الحدث.',
    closingLabel: 'ومن سؤالٍ، تبدأ الرحلة',
    closingTitle: 'الآن، للحكاية مكان.\nولرحلتك بداية.',
    closingBody: 'ادخل إلى الخريطة، وابدأ بأول فصل. خذ وقتك؛ كل حدث يفتح لك بابًا إلى ما بعده.',
    closingNote: 'بالعربية والإنجليزية · إعدادات قراءة تناسبك',
  },
  en: {
    discover: 'Discover the experience',
    begin: 'Begin the journey',
    preview: 'A glimpse of the journey',
    overviewLabel: 'A story to read. A place to discover.',
    overviewTitle: 'The Sirah,\nthrough place and time.',
    overviewBody: 'Explore the Sirah—the life of Prophet Muhammad ﷺ—through its events, places, and people. Read the story, find its setting on the map, and follow the sources to learn more.',
    overviewCaption: 'The first revelation at Hira — the event and its setting, side by side.',
    overviewAlt: 'The Journey page showing the first revelation alongside the Cave of Hira on the map.',
    tourLabel: 'How the story unfolds',
    tourTitle: 'Follow the story.\nDiscover its world.',
    tourBody: 'From one chapter to the next, events connect with places, bringing the details of the Sirah into focus.',
    steps: [
      { label: 'Read', title: 'Chapter by chapter,\nthe story unfolds.', body: 'Begin before the Prophethood, then follow the Makkan period, the Hijrah, and the Madinan period. Read in order or choose a chapter to explore.', note: 'Four chapters. One connected timeline.', caption: 'The opening of the Makkan chapter', alt: 'The Makkan chapter opening and its date range on the Journey page.' },
      { label: 'Discover', title: 'Find the places\nbehind the events.', body: 'As you read, the map follows each event and brings its location into view when it is known. See how Makkah, Madinah, and the surrounding places connect to the story.', note: 'Place and time, alongside the text.', caption: 'The Cave of Hira on the historical map', alt: 'The historical map highlighting the Cave of Hira near Makkah.' },
      { label: 'Follow', title: 'Trace the journey,\none stop at a time.', body: 'Explore the Hijrah, the journey to Ta’if, and the Farewell Hajj. Move between stops recorded in the sources and read the passage connected to each place.', note: 'Routes to explore at your own pace.', caption: 'The Hijrah route — the Cave of Thawr stop', alt: 'The Hijrah route map with the Cave of Thawr stop and its cited source passage.' },
    ],
    deeperLabel: 'There is more to every event',
    deeperTitle: 'Read. Ask.\nConnect the details.',
    deeperBody: 'When a name, a verse, or a question catches your attention, there is a way to keep exploring.',
    features: [
      { image: 'verses', title: 'Read verses in context', body: 'Find verses connected to an event or its period. Open them to read, with an explanation of how they relate.', alt: 'References to Surah Al-Alaq and Al-Muddaththir connected to the first revelation.' },
      { image: 'people', title: 'Meet the people', body: 'Open names within the story to find a cited biography and the events in which they appear.', alt: 'Khadijah bint Khuwaylid’s profile, showing her name and the opening of her cited biography.' },
      { image: 'ask', title: 'Ask the map', body: 'Ask about an event, a place, or a person. The experience searches the project’s texts and shows an answer with its source.', alt: 'A sourced answer about when the Battle of Badr took place, retrieved from the project’s texts.' },
      { image: 'quiz', title: 'Test what you discover', body: 'Pause for chapter questions and choose a place on the map. Review the answer and explanation, then continue your journey.', alt: 'A question from the Journey with a selection of map locations as possible answers.' },
    ],
    sourcesLabel: 'A story with references',
    sourcesTitle: 'Read the story.\nReturn to its source.',
    sourcesBody: 'References are part of the experience. Find them beside the text so you can trace the information and read its source.',
    sourceExample: 'Inside an event card',
    sourceExampleTitle: 'The Hijrah to Madinah',
    sourceExampleBody: 'A direct reference to the historical encyclopedia, included with the event.',
    sourceAlt: 'The Hijrah event’s source reference to the Dorar Historical Encyclopedia, event 42.',
    sources: [
      { title: 'Events of the Sirah', body: 'Passages from the Dorar Historical Encyclopedia, with references.' },
      { title: 'Hadith narrations', body: 'References to Sahih al-Bukhari and Sahih Muslim for the related records.' },
      { title: 'Verses and their connections', body: 'Tafsir references explaining the relationship between verses and events.' },
    ],
    precision: 'Some locations are approximate. The experience identifies location precision alongside each event.',
    closingLabel: 'Every journey begins with a question',
    closingTitle: 'The story has a place.\nYour journey starts here.',
    closingBody: 'Step into the map and begin with the first chapter. Take your time; each event leads you to the next.',
    closingNote: 'Arabic and English · Reading settings that suit you',
  },
};
