import { digits } from '../data/select';
import type { Locale } from '../i18n';

/** Arabic counted noun for events: حدث واحد، حدثان، ٣ أحداث، ١١ حدثًا. */
const arCount = (n: number) => n === 1 ? 'حدث واحد' : n === 2 ? 'حدثان' : n <= 10 ? `${digits(n, 'ar')} أحداث` : `${digits(n, 'ar')} حدثًا`;

export const journeyCopy = {
  ar: {
    timeline: 'الخط الزمني للسيرة',
    prev: 'الحدث السابق', next: 'الحدث التالي', play: 'تشغيل القصة', pause: 'إيقاف', story: 'القصة خطوة بخطوة',
    count: (i: number, n: number) => `${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    loading: 'جارٍ تحميل بيانات السيرة…',
    error: 'تعذّر تحميل ملفات البيانات من مجلد data. تأكد من وجودها ثم أعد تحميل الصفحة.',
    place: 'المكان', when: 'الزمان',
    precision: { exact: 'موضع محدد', approx: 'موضع تقريبي', region: 'منطقة', none: 'غير محدد على الخريطة' },
    inferred: 'المكان مستنتج من السياق ويحتاج تحققًا',
    readMore: 'تابع القراءة', readLess: 'إخفاء بقية النص',
    chapter: (n: number) => `الفصل ${digits(n, 'ar')}`, yearNav: 'أحداث هذه السنة',
    inYear: (y: string, i: number, n: number) => `${y} · الحدث ${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    undated: (n: number) => `آيات غير مؤرخة (${digits(n, 'ar')})`,
    reachedCount: (n: number) => `بلغ الإسلام ${digits(n, 'ar')} من المواضع`,
    chapterSpan: (from: string, to: string, n: number) => `${from === to ? from : `من ${from} إلى ${to}`} · ${arCount(n)}`,
    quizKicker: (n: number) => `سؤال الفصل ${digits(n, 'ar')}`, quizHint: 'اختر الإجابة، أو المس المكان على الخريطة.',
    quizRight: 'إجابة صحيحة', quizWrong: (place: string) => `الإجابة الصحيحة: ${place}`,
    quizCount: (n: number, of: number) => `السؤال ${digits(n, 'ar')} من ${digits(of, 'ar')}`, quizMore: 'سؤال آخر', quizSkip: 'تخطَّ إلى سؤال آخر',
    quizAllDone: (n: number) => `أجبت عن أسئلة هذا الفصل كلها (${digits(n, 'ar')}).`,
    quizFromAsk: (chapter: string) => `إليك سؤالًا من فصل «${chapter}»، أجب عنه من الخريطة.`, noMoreQuiz: 'لا توجد أسئلة لهذا الفصل.',
    summaryKicker: 'نهاية الرحلة', summaryTitle: 'تتبّعت سيرة النبي ﷺ من مكة إلى المدينة',
    statEvents: 'أحداث قرأتها', statPlaces: 'أماكن زرتها', statQuiz: 'إجابات صحيحة', statReached: 'مواضع بلغها الإسلام',
    restart: 'ابدأ من جديد',
    walk: (route: string) => `امشِ مع ${route}`, stopOf: (i: number, n: number) => `المحطة ${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    prevStop: 'المحطة السابقة', nextStop: 'المحطة التالية', endWalk: 'إنهاء المسار',
    toolbar: 'التنقل في القصة', fromStart: 'من البداية', chapters: 'فصول القصة', askShort: 'اسأل',
    introLabel: 'بداية الرحلة', introKicker: 'السيرة النبوية في الزمان والمكان', introTitle: 'رحلة الإسلام',
    introSub: 'من مكة إلى المدينة، حدثًا بعد حدث، كما ترويها المصادر.', begin: 'ابدأ الرحلة', skip: 'تخطَّ المقدمة',
    source: 'المصدر', dorar: 'الموسوعة التاريخية – الدرر السنية',
    verses: 'القرآن في هذا الحدث', contextVerses: 'من سياق هذه المرحلة', stageVerses: 'آيات نزلت في هذه المرحلة',
    readQuranpedia: 'اقرأ الآيات في Quranpedia', openQuranpedia: 'افتح في Quranpedia', close: 'إغلاق',
    quranpediaNote: 'النص من موسوعة Quranpedia القرآنية.', reason: 'وجه الارتباط', tafseer: 'موسوعة التفسير',
    bukhari: 'البخاري', muslim: 'مسلم', narrator: 'الراوي',
    people: 'الشخصيات في هذا الحدث', death: 'الوفاة', islamWhen: 'الإسلام', notStated: 'غير مذكور في مصادر المشروع',
    personEvents: 'أحداث ورد فيها', bioInArabic: '',
    personSource: 'ملخص موثق من مصادر المشروع (الدرر السنية والصحيحان)، وكل معلومة فيه لها مصدرها في ملف المراجع.',
    noEnglish: '',
    unplaced: 'آيات لم تحدد المصادر حدثها',
    unplacedNote: 'تذكر المصادر هذه الآيات دون ربطها بحدث معين، فلا تظهر على الخط الزمني.',
    ask: 'اسأل الخريطة',
    askNote: 'يجيب من نصوص الدرر والصحيحين فقط، ويذكر المصدر.',
    tryAsking: 'أمثلة على الأسئلة',
    suggestions: ['لماذا هاجر النبي ﷺ إلى المدينة؟', 'متى كانت غزوة بدر؟', 'من هي خديجة رضي الله عنها؟', 'اختبرني بسؤال آخر'],
    wholeSurah: 'السورة كاملة',
  },
  en: {
    timeline: 'Timeline of the Sirah',
    prev: 'Previous event', next: 'Next event', play: 'Play the story', pause: 'Pause', story: 'Story mode',
    count: (i: number, n: number) => `${i} of ${n}`,
    loading: 'Loading the Sirah data…',
    error: 'The data files could not be loaded from the data folder. Check they are there, then reload the page.',
    place: 'Place', when: 'When',
    precision: { exact: 'Exact location', approx: 'Approximate location', region: 'Region', none: 'Not on the map' },
    inferred: 'Location inferred from context; needs checking',
    readMore: 'Continue reading', readLess: 'Show less',
    chapter: (n: number) => `Chapter ${n}`, yearNav: 'Events this year',
    inYear: (y: string, i: number, n: number) => `${y} · event ${i} of ${n}`,
    undated: (n: number) => `Undated verses (${n})`,
    reachedCount: (n: number) => `Islam has reached ${n} ${n === 1 ? 'place' : 'places'}`,
    chapterSpan: (from: string, to: string, n: number) => `${from === to ? from : `${from} to ${to}`} · ${n} ${n === 1 ? 'event' : 'events'}`,
    quizKicker: (n: number) => `Chapter ${n} question`, quizHint: 'Choose an answer, or tap the place on the map.',
    quizRight: 'Correct', quizWrong: (place: string) => `The answer is ${place}`,
    quizCount: (n: number, of: number) => `Question ${n} of ${of}`, quizMore: 'Another question', quizSkip: 'Skip to another question',
    quizAllDone: (n: number) => `You have answered all ${n} questions in this chapter.`,
    quizFromAsk: (chapter: string) => `Here is a question from “${chapter}” — answer it on the map.`, noMoreQuiz: 'There are no questions for this chapter.',
    summaryKicker: 'End of the journey', summaryTitle: 'You followed the life of the Prophet ﷺ from Makkah to Madinah',
    statEvents: 'Events read', statPlaces: 'Places visited', statQuiz: 'Correct answers', statReached: 'Places Islam reached',
    restart: 'Start again',
    walk: (route: string) => `Walk ${route}`, stopOf: (i: number, n: number) => `stop ${i} of ${n}`,
    prevStop: 'Previous stop', nextStop: 'Next stop', endWalk: 'Finish the walk',
    toolbar: 'Story navigation', fromStart: 'From the start', chapters: 'Chapters', askShort: 'Ask',
    introLabel: 'The beginning of the journey', introKicker: 'The life of the Prophet ﷺ in place and time', introTitle: 'Islam Journey',
    introSub: 'From Makkah to Madinah, event by event, as the sources tell it.', begin: 'Begin the journey', skip: 'Skip the opening',
    source: 'Source', dorar: 'Dorar Historical Encyclopedia',
    verses: 'The Quran in this event', contextVerses: 'From the context of this stage', stageVerses: 'Verses revealed in this stage',
    readQuranpedia: 'Read the verses on Quranpedia', openQuranpedia: 'Open on Quranpedia', close: 'Close',
    quranpediaNote: 'Text from Quranpedia, the open Quranic encyclopedia.', reason: 'How it connects', tafseer: 'Tafsir Encyclopedia',
    bukhari: 'Bukhari', muslim: 'Muslim', narrator: 'Narrator',
    people: 'People in this event', death: 'Death', islamWhen: 'Islam', notStated: "Not stated in the project's sources",
    personEvents: 'Events they appear in', bioInArabic: "The project's cited summary and dates are in Arabic.",
    personSource: "A cited summary from the project's sources (Dorar and the Sahihayn); each fact has its source in the references file.",
    noEnglish: 'English text is not available for this event; showing the Arabic source.',
    unplaced: 'Verses with no dated event',
    unplacedNote: 'The sources mention these verses without linking them to a specific event, so they stay off the timeline.',
    ask: 'Ask the map',
    askNote: 'Answers come only from the Dorar and Sahihayn texts, with the source named.',
    tryAsking: 'Example questions',
    suggestions: ['Why did the Prophet ﷺ migrate to Madinah?', 'When was the Battle of Badr?', 'Who was Khadijah?', 'Quiz me with another question'],
    wholeSurah: 'The whole surah',
  },
} satisfies Record<Locale, unknown>;
