import { digits } from '../data/select';
import type { Locale } from '../i18n';

export const journeyCopy = {
  ar: {
    timeline: 'الخط الزمني للسيرة',
    prev: 'الحدث السابق', next: 'الحدث التالي', play: 'تشغيل القصة', pause: 'إيقاف', story: 'القصة خطوة بخطوة',
    count: (i: number, n: number) => `${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    loading: 'جارٍ تحميل بيانات السيرة…',
    error: 'تعذّر تحميل ملفات البيانات من مجلد data. تأكد من وجودها ثم أعد تحميل الصفحة.',
    place: 'المكان', when: 'الزمان',
    precision: { exact: 'موضع محدد', approx: 'موضع تقريبي', region: 'منطقة', none: 'غير محدد على الخريطة' },
    inferred: 'المكان مستنتج من السياق ويحتاج تحققًا',
    readMore: 'اقرأ النص كاملًا', readLess: 'إخفاء النص',
    source: 'المصدر', dorar: 'الموسوعة التاريخية – الدرر السنية',
    verses: 'القرآن في هذا الحدث', contextVerses: 'من سياق هذه المرحلة', stageVerses: 'آيات نزلت في هذه المرحلة',
    readMushaf: 'اقرأ في المصحف', reason: 'وجه الارتباط', tafseer: 'موسوعة التفسير',
    bukhari: 'البخاري', muslim: 'مسلم', narrator: 'الراوي',
    people: 'من الصحابة في هذا الحدث', death: 'الوفاة',
    noEnglish: '',
    unplaced: 'آيات لم تحدد المصادر حدثها',
    unplacedNote: 'تذكر المصادر هذه الآيات دون ربطها بحدث معين، فلا تظهر على الخط الزمني.',
    ask: 'اسأل الخريطة',
    askNote: 'يجيب من نصوص الدرر والصحيحين فقط، ويذكر المصدر.',
    tryAsking: 'أمثلة على الأسئلة',
    suggestions: ['لماذا هاجر النبي ﷺ إلى المدينة؟', 'متى كانت غزوة بدر؟', 'من هي خديجة رضي الله عنها؟'],
    wholeSurah: 'السورة كاملة',
  },
  en: {
    timeline: 'Timeline of the Sirah',
    prev: 'Previous event', next: 'Next event', play: 'Play the story', pause: 'Pause', story: 'Story mode',
    count: (i: number, n: number) => `${i} of ${n}`,
    loading: 'Loading the Sirah data…',
    error: 'The data files could not be loaded from the data folder. Check they are there, then reload the page.',
    place: 'Place', when: 'When',
    precision: { exact: 'Exact location', approx: 'Approximate location', region: 'Region', none: 'Not on the map' },
    inferred: 'Location inferred from context; needs checking',
    readMore: 'Read the full text', readLess: 'Hide the text',
    source: 'Source', dorar: 'Dorar Historical Encyclopedia',
    verses: 'The Quran in this event', contextVerses: 'From the context of this stage', stageVerses: 'Verses revealed in this stage',
    readMushaf: 'Read in the Mushaf', reason: 'How it connects', tafseer: 'Tafsir Encyclopedia',
    bukhari: 'Bukhari', muslim: 'Muslim', narrator: 'Narrator',
    people: 'Companions in this event', death: 'Death',
    noEnglish: 'English text is not available for this event; showing the Arabic source.',
    unplaced: 'Verses with no dated event',
    unplacedNote: 'The sources mention these verses without linking them to a specific event, so they stay off the timeline.',
    ask: 'Ask the map',
    askNote: 'Answers come only from the Dorar and Sahihayn texts, with the source named.',
    tryAsking: 'Example questions',
    suggestions: ['Why did the Prophet ﷺ migrate to Madinah?', 'When was the Battle of Badr?', 'Who was Khadijah?'],
    wholeSurah: 'The whole surah',
  },
} satisfies Record<Locale, unknown>;
