import { digits } from '../data/select';
import type { Locale } from '../i18n';

export const journeyCopy = {
  ar: {
    timeline: 'الخط الزمني للسيرة',
    prev: 'الحدث السابق', next: 'الحدث التالي', play: 'تشغيل القصة', pause: 'إيقاف', story: 'القصة خطوة بخطوة',
    count: (i: number, n: number) => `${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    loading: 'جارٍ تحميل بيانات السيرة…',
    error: 'تعذّر تحميل ملفات البيانات من مجلد data. تأكد من وجودها ثم أعد تحميل الصفحة.',
    place: 'المكان', when: 'الزمان',
    precision: { exact: 'موضع محدد', approx: 'موضع تقريبي', region: 'منطقة', none: 'غير محدد على الخريطة' },
    inferred: 'المكان مستنتج من السياق ويحتاج تحققًا',
    readMore: 'تابع القراءة', readLess: 'إخفاء بقية النص',
    chapter: (n: number) => `الفصل ${digits(n, 'ar')}`, yearNav: 'أحداث هذه السنة',
    inYear: (y: string, i: number, n: number) => `${y} · الحدث ${digits(i, 'ar')} من ${digits(n, 'ar')}`,
    undated: (n: number) => `آيات غير مؤرخة (${digits(n, 'ar')})`,
    reachedCount: (n: number) => `بلغ الإسلام ${digits(n, 'ar')} من المواضع`,
    source: 'المصدر', dorar: 'الموسوعة التاريخية – الدرر السنية',
    verses: 'القرآن في هذا الحدث', contextVerses: 'من سياق هذه المرحلة', stageVerses: 'آيات نزلت في هذه المرحلة',
    readQuranpedia: 'اقرأ الآيات في Quranpedia', openQuranpedia: 'افتح في Quranpedia', close: 'إغلاق',
    quranpediaNote: 'النص من موسوعة Quranpedia القرآنية.', reason: 'وجه الارتباط', tafseer: 'موسوعة التفسير',
    bukhari: 'البخاري', muslim: 'مسلم', narrator: 'الراوي',
    people: 'الشخصيات في هذا الحدث', death: 'الوفاة', islamWhen: 'الإسلام', notStated: 'غير مذكور في مصادر المشروع',
    personEvents: 'أحداث ورد فيها', bioInArabic: '',
    personSource: 'ملخص موثق من مصادر المشروع (الدرر السنية والصحيحان)، وكل معلومة فيه لها مصدرها في ملف المراجع.',
    noEnglish: '',
    unplaced: 'آيات لم تحدد المصادر حدثها',
    unplacedNote: 'تذكر المصادر هذه الآيات دون ربطها بحدث معين، فلا تظهر على الخط الزمني.',
    ask: 'اسأل الخريطة',
    askNote: 'يجيب من نصوص الدرر والصحيحين فقط، ويذكر المصدر.',
    tryAsking: 'أمثلة على الأسئلة',
    suggestions: ['لماذا هاجر النبي ﷺ إلى المدينة؟', 'متى كانت غزوة بدر؟', 'من هي خديجة رضي الله عنها؟'],
    wholeSurah: 'السورة كاملة',
  },
  en: {
    timeline: 'Timeline of the Sirah',
    prev: 'Previous event', next: 'Next event', play: 'Play the story', pause: 'Pause', story: 'Story mode',
    count: (i: number, n: number) => `${i} of ${n}`,
    loading: 'Loading the Sirah data…',
    error: 'The data files could not be loaded from the data folder. Check they are there, then reload the page.',
    place: 'Place', when: 'When',
    precision: { exact: 'Exact location', approx: 'Approximate location', region: 'Region', none: 'Not on the map' },
    inferred: 'Location inferred from context; needs checking',
    readMore: 'Continue reading', readLess: 'Show less',
    chapter: (n: number) => `Chapter ${n}`, yearNav: 'Events this year',
    inYear: (y: string, i: number, n: number) => `${y} · event ${i} of ${n}`,
    undated: (n: number) => `Undated verses (${n})`,
    reachedCount: (n: number) => `Islam has reached ${n} ${n === 1 ? 'place' : 'places'}`,
    source: 'Source', dorar: 'Dorar Historical Encyclopedia',
    verses: 'The Quran in this event', contextVerses: 'From the context of this stage', stageVerses: 'Verses revealed in this stage',
    readQuranpedia: 'Read the verses on Quranpedia', openQuranpedia: 'Open on Quranpedia', close: 'Close',
    quranpediaNote: 'Text from Quranpedia, the open Quranic encyclopedia.', reason: 'How it connects', tafseer: 'Tafsir Encyclopedia',
    bukhari: 'Bukhari', muslim: 'Muslim', narrator: 'Narrator',
    people: 'People in this event', death: 'Death', islamWhen: 'Islam', notStated: "Not stated in the project's sources",
    personEvents: 'Events they appear in', bioInArabic: "The project's cited summary and dates are in Arabic.",
    personSource: "A cited summary from the project's sources (Dorar and the Sahihayn); each fact has its source in the references file.",
    noEnglish: 'English text is not available for this event; showing the Arabic source.',
    unplaced: 'Verses with no dated event',
    unplacedNote: 'The sources mention these verses without linking them to a specific event, so they stay off the timeline.',
    ask: 'Ask the map',
    askNote: 'Answers come only from the Dorar and Sahihayn texts, with the source named.',
    tryAsking: 'Example questions',
    suggestions: ['Why did the Prophet ﷺ migrate to Madinah?', 'When was the Battle of Badr?', 'Who was Khadijah?'],
    wholeSurah: 'The whole surah',
  },
} satisfies Record<Locale, unknown>;
