// Build src/data/land.ts: the land/sea outline (Natural Earth 1:50m, via world-atlas)
// clipped to the Sirah region and projected to SVG units. Coastlines only — no
// political borders are drawn, so no country outline is approximated.
// Run: node scripts/build-land.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { feature } from 'topojson-client';

const BOX = { west: 28, east: 53, south: 10, north: 36 };
const K = 40; // SVG units per degree of latitude
const COS = Math.cos(((BOX.south + BOX.north) / 2) * Math.PI / 180);
const project = ([lon, lat]) => [(lon - BOX.west) * COS * K, (BOX.north - lat) * K];

// Sutherland–Hodgman clip of one ring against the box (in degrees).
function clip(ring) {
  const edges = [
    [p => p[0] >= BOX.west, (a, b) => cut(a, b, 0, BOX.west)],
    [p => p[0] <= BOX.east, (a, b) => cut(a, b, 0, BOX.east)],
    [p => p[1] >= BOX.south, (a, b) => cut(a, b, 1, BOX.south)],
    [p => p[1] <= BOX.north, (a, b) => cut(a, b, 1, BOX.north)],
  ];
  let out = ring;
  for (const [inside, hit] of edges) {
    const input = out; out = [];
    for (let i = 0; i < input.length; i++) {
      const cur = input[i], prev = input[(i + input.length - 1) % input.length];
      if (inside(cur)) { if (!inside(prev)) out.push(hit(prev, cur)); out.push(cur); }
      else if (inside(prev)) out.push(hit(prev, cur));
    }
    if (!out.length) break;
  }
  return out;
}
function cut(a, b, axis, v) {
  const t = (v - a[axis]) / (b[axis] - a[axis]);
  return [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t];
}

const topo = JSON.parse(readFileSync(new URL('../node_modules/world-atlas/land-50m.json', import.meta.url)));
const land = feature(topo, topo.objects.land);
const polys = land.type === 'FeatureCollection' ? land.features.flatMap(f => f.geometry.coordinates) : land.geometry.coordinates;
let d = '';
for (const poly of polys) for (const ring of poly) {
  const c = clip(ring);
  if (c.length < 3) continue;
  d += 'M' + c.map(p => project(p).map(v => v.toFixed(1)).join(' ')).join('L') + 'Z';
}
const [W, H] = project([BOX.east, BOX.south]);
writeFileSync(new URL('../src/data/land.ts', import.meta.url),
  `// Generated by scripts/build-land.mjs — Natural Earth 1:50m land, public domain.\n` +
  `export const BOX = ${JSON.stringify(BOX)};\nexport const K = ${K};\nexport const COS = ${COS};\n` +
  `export const WIDTH = ${W.toFixed(1)};\nexport const HEIGHT = ${H.toFixed(1)};\n` +
  `export const LAND = '${d}';\n`);
console.log(`land.ts: ${(d.length / 1024).toFixed(0)} KB path, ${W.toFixed(0)}×${H.toFixed(0)}`);
