const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = process.argv[2] || 'http://127.0.0.1:5173';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const errors = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'no-preference' });
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(base);
    await page.waitForSelector('.logo-transition', { state: 'detached' });
    await page.waitForTimeout(700);
    await page.screenshot({ path: 'qa/landing-motion-hero.png' });
    for (const locale of ['en', 'ar']) {
      await page.locator('.language-switch').click();
      await page.waitForFunction(locale => document.documentElement.lang === locale, locale);
      await page.waitForTimeout(220);
      assert.equal(await page.locator('html').getAttribute('data-language-sweep'), locale);
      const name = await page.evaluate(() => getComputedStyle(document.documentElement, '::view-transition-new(root)').animationName);
      assert.equal(name, locale === 'en' ? 'language-sweep-ltr' : 'language-sweep-rtl');
      await page.screenshot({ path: `qa/landing-sweep-${locale}.png` });
      await page.waitForFunction(() => !document.documentElement.dataset.languageSweep);
      assert.equal(await page.locator('html').getAttribute('dir'), locale === 'ar' ? 'rtl' : 'ltr');
    }
    await page.locator('.language-switch').evaluate(button => { button.click(); button.click(); button.click(); });
    await page.waitForFunction(() => document.documentElement.lang === 'en' && !document.documentElement.dataset.languageSweep);
    console.log('PASS both sweep directions and rapid toggles');
    await page.locator('.landing-deeper').evaluate(el => el.scrollIntoView({ block: 'start' }));
    await page.waitForTimeout(180);
    assert.ok(await page.evaluate(() => document.getAnimations().some(a => a.playState === 'running')));
    await page.waitForTimeout(800);
    const top = await page.locator('.landing-deeper').evaluate(el => el.getBoundingClientRect().top);
    await page.locator('.language-switch').evaluate(button => button.click());
    await page.waitForFunction(() => document.documentElement.lang === 'ar' && !document.documentElement.dataset.languageSweep);
    const after = await page.locator('.landing-deeper').evaluate(el => el.getBoundingClientRect().top);
    assert.ok(Math.abs(top - after) < 3, `Reading position moved: ${top} -> ${after}`);
    const progress = await page.locator('.landing-progress').evaluate(el => Number(el.style.getPropertyValue('--landing-progress')));
    assert.ok(progress > 0 && progress < 1);
    console.log('PASS section entrances, scroll position and reading progress');
    await page.locator('.language-switch').evaluate(button => button.click());
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.waitForFunction(() => document.documentElement.dataset.reducedMotion === 'true' && !document.documentElement.dataset.languageSweep);
    await page.waitForTimeout(150);
    assert.equal(await page.evaluate(() => document.getAnimations().filter(a => a.playState === 'running').length), 0);
    await page.locator('.language-switch').evaluate(button => button.click());
    await page.waitForFunction(() => document.documentElement.lang === 'ar');
    assert.equal(await page.locator('html').getAttribute('data-language-sweep'), null);
    console.log('PASS reduced motion, including changes during a sweep');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.locator('.language-switch').focus();
    await page.keyboard.press('Enter');
    await page.waitForFunction(() => document.documentElement.lang === 'en' && !document.documentElement.dataset.languageSweep);
    assert.ok(await page.evaluate(() => document.activeElement.classList.contains('language-switch')));
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1));
    await page.screenshot({ path: 'qa/landing-motion-mobile.png' });
    console.log('PASS mobile layout and keyboard focus');
    // The single shared language switch also works on Journey.
    await page.evaluate(() => sessionStorage.setItem('bidaya.intro.seen', '1'));
    await page.goto(`${base}/journey`);
    await page.waitForSelector('.logo-transition', { state: 'detached' });
    await page.locator('.language-switch').click();
    await page.waitForFunction(() => document.documentElement.lang === 'en' && !document.documentElement.dataset.languageSweep);
    assert.ok(await page.locator('.scrolly-map').isVisible());
    console.log('PASS Journey header language sweep');
    await page.close();
    const fallback = await browser.newPage({ reducedMotion: 'no-preference' });
    fallback.on('pageerror', error => errors.push(error.message));
    await fallback.addInitScript(() => Object.defineProperty(document, 'startViewTransition', { value: undefined }));
    await fallback.goto(base);
    await fallback.waitForSelector('.logo-transition', { state: 'detached' });
    await fallback.locator('.language-switch').click();
    await fallback.waitForFunction(() => document.documentElement.lang === 'en');
    assert.equal(await fallback.locator('html').getAttribute('data-language-sweep'), null);
    await fallback.close();
    assert.deepEqual(errors, []);
    console.log('PASS fallback without View Transitions and no browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
